spring:
  application:
    name: RedisExampleApp

  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

# Redis ??? ?? ?? ?? ??
logging:
  level:
    org.springframework.cache: trace
